# Generated by Django 4.2.4 on 2023-08-06 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=10)),
                ('tole', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Achham', 'Achham'), ('Arghakhanchi', 'Arghakhanchi'), ('Baglung', 'Baglung'), ('Baitadi', 'Baitadi'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Banke', 'Banke'), ('Bara', 'Bara'), ('Bardiya', 'Bardiya'), ('Bhaktapur', 'Bhaktapur'), ('Bhojpur', 'Bhojpur'), ('Chitwan', 'Chitwan'), ('Dadeldhura', 'Dadeldhura'), ('Dailekh', 'Dailekh'), ('Dang Deukhuri', 'Dang Deukhuri'), ('Darchula', 'Darchula'), ('Dhading', 'Dhading'), ('Dhankuta', 'Dhankuta'), ('Dhanusa', 'Dhanusa'), ('Dholkha', 'Dholkha'), ('Dolpa', 'Dolpa'), ('Doti', 'Doti'), ('Gorkha', 'Gorkha'), ('Gulmi', 'Gulmi'), ('Humla', 'Humla'), ('Ilam', 'Ilam'), ('Jajarkot', 'Jajarkot'), ('Jhapa', 'Jhapa'), ('Jumla', 'Jumla'), ('Kailali', 'Kailali'), ('Kalikot', 'Kalikot'), ('Kanchanpur', 'Kanchanpur'), ('Kapilvastu', 'Kapilvastu'), ('Kaski', 'Kaski'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Khotang', 'Khotang'), ('Lalitpur', 'Lalitpur'), ('Lamjung', 'Lamjung'), ('Mahottari', 'Mahottari'), ('Makwanpur', 'Makwanpur'), ('Manang', 'Manang'), ('Morang', 'Morang'), ('Mugu', 'Mugu'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalpur', 'Nawalpur'), ('Nuwakot', 'Nuwakot'), ('Okhaldhunga', 'Okhaldhunga'), ('Palpa', 'Palpa'), ('Panchthar', 'Panchthar'), ('Parbat', 'Parbat'), ('Parsa', 'Parsa'), ('Pyuthan', 'Pyuthan'), ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Rautahat', 'Rautahat'), ('Rolpa', 'Rolpa'), ('Rukum Eastern', 'Rukum Eastern'), ('Rukum Western', 'Rukum Western'), ('Rupandehi', 'Rupandehi'), ('Salyan', 'Salyan'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'), ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok'), ('Siraha', 'Siraha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Surkhet', 'Surkhet'), ('Syangja', 'Syangja'), ('Tanahu', 'Tanahu'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Rukum Central', 'Rukum Central')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Koshi Pradesh', 'Koshi Pradesh'), ('Madesh Pradesh', 'Madesh Pradesh'), ('Bagmati Pradesh', 'Bagmati Pradesh'), ('Gandaki Pradesh', 'Gandaki Pradesh'), ('Lumbini Pradesh', 'Lumbini Pradesh'), ('Karnali Pradesh', 'Karnali Pradesh')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person/images')),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_address', to='store.address')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_address', to='store.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workplace_address', to='store.address')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Pokhara', 'Pokhara'), ('Biratnagar', 'Biratnagar'), ('Birgunj', 'Birgunj'), ('Dharan', 'Dharan'), ('Butwal', 'Butwal'), ('Bharatpur', 'Bharatpur'), ('Hetauda', 'Hetauda'), ('Janakpur', 'Janakpur'), ('Dhangadhi', 'Dhangadhi'), ('Nepalgunj', 'Nepalgunj'), ('Itahari', 'Itahari'), ('Tulsipur', 'Tulsipur'), ('Siddharthanagar', 'Siddharthanagar'), ('Ghorahi', 'Ghorahi'), ('Bhimdatta', 'Bhimdatta'), ('Rajbiraj', 'Rajbiraj'), ('Tansen', 'Tansen'), ('Madhyapur Thimi', 'Madhyapur Thimi'), ('Panauti', 'Panauti'), ('Gorkha', 'Gorkha'), ('Ilam', 'Ilam'), ('Damak', 'Damak'), ('Banepa', 'Banepa'), ('Dhankuta', 'Dhankuta'), ('Dhulikhel', 'Dhulikhel'), ('Lahan', 'Lahan'), ('Siddharthanagar', 'Siddharthanagar'), ('Rajbiraj', 'Rajbiraj'), ('Inaruwa', 'Inaruwa'), ('Itahari', 'Itahari'), ('Kirtipur', 'Kirtipur'), ('Lahan', 'Lahan'), ('Rajbiraj', 'Rajbiraj'), ('Siddharthanagar', 'Siddharthanagar'), ('Tansen', 'Tansen'), ('Chitlang', 'Chitlang'), ('Bandipur', 'Bandipur'), ('Lwang Ghalel', 'Lwang Ghalel'), ('Ghandruk', 'Ghandruk'), ('Ghale Gaun', 'Ghale Gaun'), ('Kagbeni', 'Kagbeni'), ('Manang', 'Manang'), ('Marpha', 'Marpha'), ('Muktinath', 'Muktinath'), ('Tsum Valley', 'Tsum Valley'), ('Bhulbhule', 'Bhulbhule'), ('Dana', 'Dana'), ('Ghermu', 'Ghermu'), ('Khudi', 'Khudi'), ('Syange', 'Syange'), ('Tatopani', 'Tatopani'), ('Machhapuchhre', 'Machhapuchhre'), ('Madi', 'Madi'), ('Bhorle', 'Bhorle'), ('Chhang', 'Chhang'), ('Mirkot', 'Mirkot'), ('Jaimakasala', 'Jaimakasala'), ('Dudhpokhari', 'Dudhpokhari'), ('Kathar', 'Kathar'), ('Dhaulagiri', 'Dhaulagiri'), ('Jaljala', 'Jaljala'), ('Nisikhola', 'Nisikhola'), ('Raghuganga', 'Raghuganga'), ('Gurans', 'Gurans'), ('Beni', 'Beni'), ('Budhiganga', 'Budhiganga'), ('Malika', 'Malika'), ('Lumle', 'Lumle'), ('Kande', 'Kande'), ('Lamachaur', 'Lamachaur'), ('Lekhnath', 'Lekhnath'), ('Lekhnath', 'Lekhnath'), ('Ganeshman Charnath', 'Ganeshman Charnath'), ('Kathahariya', 'Kathahariya'), ('Shivaraj', 'Shivaraj'), ('Mainapokhar', 'Mainapokhar'), ('Shambhunath', 'Shambhunath'), ('Gangawati', 'Gangawati'), ('Dhankuta', 'Dhankuta'), ('Tehrathum', 'Tehrathum'), ('Hile', 'Hile'), ('Phungling', 'Phungling'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Bhojpur', 'Bhojpur'), ('Udayapur', 'Udayapur'), ('Katari', 'Katari'), ('Okhaldhunga', 'Okhaldhunga'), ('Siddhicharan', 'Siddhicharan'), ('Taplejung', 'Taplejung'), ('Ilam', 'Ilam'), ('Fikkal', 'Fikkal'), ('Khotang', 'Khotang'), ('Sotang', 'Sotang'), ('Ramechhap', 'Ramechhap'), ('Phulasi', 'Phulasi'), ('Halesi', 'Halesi')], max_length=50, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='store.province'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province'),
        ),
    ]
