# Generated by Django 4.2.4 on 2023-10-21 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tole', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=20)),
                ('local_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Achham', 'Achham'), ('Arghakhanchi', 'Arghakhanchi'), ('Baglung', 'Baglung'), ('Baitadi', 'Baitadi'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Banke', 'Banke'), ('Bara', 'Bara'), ('Bardiya', 'Bardiya'), ('Bhaktapur', 'Bhaktapur'), ('Bhojpur', 'Bhojpur'), ('Chitwan', 'Chitwan'), ('Dadeldhura', 'Dadeldhura'), ('Dailekh', 'Dailekh'), ('Dang Deukhuri', 'Dang Deukhuri'), ('Darchula', 'Darchula'), ('Dhading', 'Dhading'), ('Dhankuta', 'Dhankuta'), ('Dhanusa', 'Dhanusa'), ('Dholkha', 'Dholkha'), ('Dolpa', 'Dolpa'), ('Doti', 'Doti'), ('Gorkha', 'Gorkha'), ('Gulmi', 'Gulmi'), ('Humla', 'Humla'), ('Ilam', 'Ilam'), ('Jajarkot', 'Jajarkot'), ('Jhapa', 'Jhapa'), ('Jumla', 'Jumla'), ('Kailali', 'Kailali'), ('Kalikot', 'Kalikot'), ('Kanchanpur', 'Kanchanpur'), ('Kapilvastu', 'Kapilvastu'), ('Kaski', 'Kaski'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Khotang', 'Khotang'), ('Lalitpur', 'Lalitpur'), ('Lamjung', 'Lamjung'), ('Mahottari', 'Mahottari'), ('Makwanpur', 'Makwanpur'), ('Manang', 'Manang'), ('Morang', 'Morang'), ('Mugu', 'Mugu'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalpur', 'Nawalpur'), ('Nuwakot', 'Nuwakot'), ('Okhaldhunga', 'Okhaldhunga'), ('Palpa', 'Palpa'), ('Panchthar', 'Panchthar'), ('Parbat', 'Parbat'), ('Parsa', 'Parsa'), ('Pyuthan', 'Pyuthan'), ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Rautahat', 'Rautahat'), ('Rolpa', 'Rolpa'), ('Rukum Eastern', 'Rukum Eastern'), ('Rukum Western', 'Rukum Western'), ('Rupandehi', 'Rupandehi'), ('Salyan', 'Salyan'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'), ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok'), ('Siraha', 'Siraha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Surkhet', 'Surkhet'), ('Syangja', 'Syangja'), ('Tanahu', 'Tanahu'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Rukum Central', 'Rukum Central')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDonorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='gallery/thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sanfebagar', 'Sanfebagar'), ('Mangalsen', 'Mangalsen'), ('KamalBazar', 'KamalBazar'), ('Panchadewal Binayak', 'Panchadewal Binayak'), ('Ramaroshan', 'Ramaroshan'), ('Chaurpati', 'Chaurpati'), (' Turmakhand', 'Turmakhand'), ('Mellekh', 'Mellekh'), ('Dhakari', 'Dhakari'), ('Bannigadi Jayagad', 'Bannigadi Jayagad')], max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.CharField(blank=True, max_length=100, null=True)),
                ('workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person/images')),
                ('latest_donation', models.DateField(blank=True, null=True)),
                ('latest_received', models.DateField(blank=True, null=True)),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_address', to='store.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Koshi Pradesh', 'Koshi Pradesh'), ('Madesh Pradesh', 'Madesh Pradesh'), ('Bagmati Pradesh', 'Bagmati Pradesh'), ('Gandaki Pradesh', 'Gandaki Pradesh'), ('Lumbini Pradesh', 'Lumbini Pradesh'), ('Karnali Pradesh', 'Karnali Pradesh'), ('Sudurpashchim Pradesh', 'Sudurpashchim Pradesh')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors/images')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('15', '14'), ('15', '15')], max_length=50, unique=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.municipality')),
            ],
            options={
                'unique_together': {('name', 'ward_number')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('tole', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='volunteerrequest/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ward')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.person')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityQuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDonorOrganizationQuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.emergencydonororganization')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDonorOrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.emergencydonororganization')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province'),
        ),
        migrations.CreateModel(
            name='BloodDonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('tole', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donerrequest/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateVolunteerQuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associatevolunteer')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateVolunteerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address', models.CharField(max_length=255)),
                ('current_address', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associatevolunteer')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateHospitalQuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associatehospital')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateHospitalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address', models.CharField(max_length=255)),
                ('current_address', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associatehospital')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='store.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, to='store.municipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province'),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.CASCADE, to='store.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('province', 'name')},
        ),
    ]
