# Generated by Django 4.2.4 on 2023-10-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonorrequest',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
