# Generated by Django 4.2.4 on 2023-08-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_district_province_alter_municipality_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Pokhara', 'Pokhara'), ('Biratnagar', 'Biratnagar'), ('Birgunj', 'Birgunj'), ('Dharan', 'Dharan'), ('Butwal', 'Butwal'), ('Bharatpur', 'Bharatpur'), ('Hetauda', 'Hetauda'), ('Janakpur', 'Janakpur'), ('Dhangadhi', 'Dhangadhi'), ('Nepalgunj', 'Nepalgunj'), ('Itahari', 'Itahari'), ('Tulsipur', 'Tulsipur'), ('Siddharthanagar', 'Siddharthanagar'), ('Ghorahi', 'Ghorahi'), ('Bhimdatta', 'Bhimdatta'), ('Rajbiraj', 'Rajbiraj'), ('Tansen', 'Tansen'), ('Madhyapur Thimi', 'Madhyapur Thimi'), ('Panauti', 'Panauti'), ('Gorkha', 'Gorkha'), ('Ilam', 'Ilam'), ('Damak', 'Damak'), ('Banepa', 'Banepa'), ('Dhankuta', 'Dhankuta'), ('Dhulikhel', 'Dhulikhel'), ('Lahan', 'Lahan'), ('Siddharthanagar', 'Siddharthanagar'), ('Rajbiraj', 'Rajbiraj'), ('Inaruwa', 'Inaruwa'), ('Itahari', 'Itahari'), ('Kirtipur', 'Kirtipur'), ('Lahan', 'Lahan'), ('Rajbiraj', 'Rajbiraj'), ('Siddharthanagar', 'Siddharthanagar'), ('Tansen', 'Tansen'), ('Chitlang', 'Chitlang'), ('Bandipur', 'Bandipur'), ('Lwang Ghalel', 'Lwang Ghalel'), ('Ghandruk', 'Ghandruk'), ('Ghale Gaun', 'Ghale Gaun'), ('Kagbeni', 'Kagbeni'), ('Manang', 'Manang'), ('Marpha', 'Marpha'), ('Muktinath', 'Muktinath'), ('Tsum Valley', 'Tsum Valley'), ('Bhulbhule', 'Bhulbhule'), ('Dana', 'Dana'), ('Ghermu', 'Ghermu'), ('Khudi', 'Khudi'), ('Syange', 'Syange'), ('Tatopani', 'Tatopani'), ('Machhapuchhre', 'Machhapuchhre'), ('Madi', 'Madi'), ('Bhorle', 'Bhorle'), ('Chhang', 'Chhang'), ('Mirkot', 'Mirkot'), ('Jaimakasala', 'Jaimakasala'), ('Dudhpokhari', 'Dudhpokhari'), ('Kathar', 'Kathar'), ('Dhaulagiri', 'Dhaulagiri'), ('Jaljala', 'Jaljala'), ('Nisikhola', 'Nisikhola'), ('Raghuganga', 'Raghuganga'), ('Gurans', 'Gurans'), ('Beni', 'Beni'), ('Budhiganga', 'Budhiganga'), ('Malika', 'Malika'), ('Lumle', 'Lumle'), ('Kande', 'Kande'), ('Lamachaur', 'Lamachaur'), ('Lekhnath', 'Lekhnath'), ('Lekhnath', 'Lekhnath'), ('Ganeshman Charnath', 'Ganeshman Charnath'), ('Kathahariya', 'Kathahariya'), ('Shivaraj', 'Shivaraj'), ('Mainapokhar', 'Mainapokhar'), ('Shambhunath', 'Shambhunath'), ('Gangawati', 'Gangawati'), ('Dhankuta', 'Dhankuta'), ('Tehrathum', 'Tehrathum'), ('Hile', 'Hile'), ('Phungling', 'Phungling'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Bhojpur', 'Bhojpur'), ('Udayapur', 'Udayapur'), ('Katari', 'Katari'), ('Okhaldhunga', 'Okhaldhunga'), ('Siddhicharan', 'Siddhicharan'), ('Taplejung', 'Taplejung'), ('Ilam', 'Ilam'), ('Fikkal', 'Fikkal'), ('Khotang', 'Khotang'), ('Sotang', 'Sotang'), ('Ramechhap', 'Ramechhap'), ('Phulasi', 'Phulasi'), ('Halesi', 'Halesi')], max_length=50)),
                ('ward_number', models.IntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.municipality')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ward'),
        ),
    ]
