# Generated by Django 4.2.4 on 2023-10-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_blooddonorrequest_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='current_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
