# Generated by Django 4.2.4 on 2023-08-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_person_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.municipality'),
        ),
    ]
