# Generated by Django 4.2.4 on 2023-08-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality'),
        ),
    ]
