# Generated by Django 4.2.4 on 2023-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
