# Generated by Django 4.2.4 on 2023-11-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_contactus_message_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
