# Generated by Django 4.2.4 on 2023-08-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
