# Generated by Django 4.2.4 on 2023-08-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_userreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
    ]
