# Generated by Django 4.2.4 on 2023-08-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profission_type', models.CharField(choices=[('Army', 'Army'), ('Police', 'Police'), ('APF', 'APF'), ('General Public', 'General Public')], max_length=50)),
            ],
        ),
    ]
