# Generated by Django 4.2.4 on 2023-08-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_emergencydonor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencydonor',
            old_name='profission_type',
            new_name='profession_type',
        ),
    ]
