# Generated by Django 4.2.4 on 2023-08-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_associatehospital_associatehospitalmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatehospitalmember',
            name='organization',
        ),
        migrations.AddField(
            model_name='associatehospitalmember',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.associatehospital'),
            preserve_default=False,
        ),
    ]
