# Generated by Django 4.2.4 on 2023-08-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_associatehospitalmember_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDonorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDonorOrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.emergencydonororganization')),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyDonor',
        ),
    ]
