# Generated by Django 4.2.4 on 2023-08-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_emergencydonororganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('tole', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donerrequest/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ward')),
            ],
        ),
    ]
