# Generated by Django 4.2.4 on 2023-08-12 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_blooddonorrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 10, 10, 45, 171213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
