# Generated by Django 4.2.4 on 2023-08-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_remove_person_age_person_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('tole', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='volunteerrequest/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ward')),
            ],
        ),
    ]
