# Generated by Django 4.2.4 on 2023-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='temporary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
