# Generated by Django 4.2.4 on 2023-09-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_address_temporary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='temporary',
            new_name='local_name',
        ),
    ]
