# Generated by Django 4.2.4 on 2023-09-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_temporary_address_local_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.CharField(max_length=200),
        ),
    ]
