# Generated by Django 4.2.4 on 2023-10-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_province_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latest_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
