# Generated by Django 4.2.4 on 2023-10-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_person_latest_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateVolunteerQuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associatevolunteer')),
            ],
        ),
    ]
