# Generated by Django 4.2.4 on 2023-10-16 14:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_municipalityquickcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='store.district'),
        ),
    ]
