# Generated by Django 4.2.4 on 2023-10-19 17:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latest_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, to='store.municipality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.CASCADE, to='store.ward'),
        ),
    ]
