# Generated by Django 4.2.4 on 2023-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_person_latest_received_alter_address_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(choices=[('Sanfebagar', 'Sanfebagar'), ('Mangalsen', 'Mangalsen'), ('KamalBazar', 'KamalBazar'), ('Panchadewal Binayak', 'Panchadewal Binayak'), ('Ramaroshan', 'Ramaroshan'), ('Chaurpati', 'Chaurpati'), (' Turmakhand', 'Turmakhand'), ('Mellekh', 'Mellekh'), ('Dhakari', 'Dhakari'), ('Bannigadi Jayagad', 'Bannigadi Jayagad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_number',
            field=models.CharField(choices=[('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No'), ('Ward No', 'Ward No')], max_length=50),
        ),
    ]
