# Generated by Django 4.2.4 on 2023-10-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_municipality_name_alter_ward_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_number',
            field=models.CharField(choices=[('Ward No', '1'), ('Ward No', '2'), ('Ward No', '3'), ('Ward No', '4'), ('Ward No', '5'), ('Ward No', '6'), ('Ward No', '7'), ('Ward No', '8'), ('Ward No', '9'), ('Ward No', '10'), ('Ward No', '11'), ('Ward No', '12'), ('Ward No', '13'), ('Ward No', '14'), ('Ward No', '15')], max_length=50),
        ),
    ]
