# Generated by Django 4.2.4 on 2023-10-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_ward_ward_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('15', '14'), ('15', '15')], max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('name', 'ward_number')},
        ),
    ]
