# Generated by Django 4.2.4 on 2023-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dooner',
            field=models.BooleanField(default=True),
        ),
    ]
