# Generated by Django 4.2.4 on 2023-08-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_dooner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_dooner',
            new_name='is_donor',
        ),
    ]
