# Generated by Django 4.2.4 on 2023-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_dooner_user_is_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_emergency_donor',
            field=models.BooleanField(default=False),
        ),
    ]
