# Generated by Django 4.2.4 on 2023-08-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_is_emergency_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
